# Generated by Django 5.1.2 on 2025-04-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_passwordresetcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
