# Generated by Django 5.1.2 on 2025-04-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='eliminada',
            field=models.BooleanField(default=False),
        ),
    ]
