# Generated by Django 5.1.2 on 2025-04-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='usuario',
        ),
        migrations.AddField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(default='Recurso sin nombre', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
