# Generated by Django 5.1.2 on 2025-04-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_remove_recurso_usuario_recurso_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(default='Recurso sin nombre', max_length=100),
        ),
    ]
