# Generated by Django 5.1.2 on 2025-04-21 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_alter_recurso_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='fecha_subida',
            new_name='fecha_agregado',
        ),
    ]
