# Generated by Django 5.1.2 on 2025-04-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_rename_user_perfilestudiante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cursos_asignados',
            field=models.ManyToManyField(blank=True, related_name='docentes_asignados', to='usuarios.curso'),
        ),
    ]
