# Generated by Django 5.1.2 on 2025-04-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_remove_curso_docente_cursodocente'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='total_unidades',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='curso',
            name='unidades_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
