# Generated by Django 5.1.2 on 2025-04-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_curso_total_unidades_curso_unidades_completadas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cursos_asignados',
        ),
    ]
