# Generated by Django 5.1.2 on 2025-04-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_remove_perfil_cursos_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodocente',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
