# Generated by Django 5.1.2 on 2025-04-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_cursoinscrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/'),
        ),
        migrations.AddField(
            model_name='curso',
            name='total_sesiones',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
