# Generated by Django 5.1.2 on 2025-05-20 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0027_curso_calificacion_curso_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
