# Generated by Django 5.1.2 on 2025-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_alter_curso_calificacion_alter_curso_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoinscrito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
