# Generated by Django 5.1.2 on 2025-05-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_calificacioncurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='visto',
            field=models.BooleanField(default=False),
        ),
    ]
