# Generated by Django 5.1.2 on 2025-05-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_categoria_curso_categoria_delete_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
