# Generated by Django 5.1.2 on 2025-05-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_perfil_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='especialidad',
        ),
    ]
