# Generated by Django 5.1.2 on 2025-05-29 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_remove_perfil_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='categoria_aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
