# Generated by Django 5.1.2 on 2025-05-29 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0040_perfil_categoria_perfil_categoria_aprobada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='categoria_aprobada',
        ),
    ]
