# Generated by Django 5.1.2 on 2025-05-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_remove_perfil_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.categoria'),
        ),
    ]
