# Generated by Django 5.1.2 on 2025-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0042_perfil_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursoinscrito',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cursoinscrito',
            name='numero_transaccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
